import { SeoReport, SeoIssue } from '../../src/types';

export function buildSeoReportObject(params?: Partial<SeoReport>): SeoReport {
  const now = new Date().toISOString();
  return {
    reportId: params?.reportId || `rep_${Date.now()}`,
    reportType: params?.reportType || 'ON_DEMAND',
    period: params?.period || { start: now, end: now },
    generatedAt: now,
    generatedBy: params?.generatedBy || 'AERO_SEO_ENGINE',
    health: params?.health || {
      overall: 92,
      technical: 95,
      indexability: 90,
      discovery: 91
    },
    indexation: params?.indexation || {
      indexable: 250,
      indexed: 245,
      excluded: 5
    },
    issues: params?.issues || {
      critical: 0,
      high: 1,
      medium: 3,
      low: 2
    },
    discovery: params?.discovery || {
      organicSessions: 14200,
      organicUsers: 11800,
      organicViews: 32500,
      organicDownloads: 8400,
      downloadConversion: 25.85
    },
    worker: params?.worker || {
      queued: 0,
      processing: 0,
      completed: 148,
      failed: 0,
      deadLetter: 0,
      retryCount: 2,
      averageProcessingMs: 180
    },
    performance: params?.performance || {
      pageP95Ms: 142,
      metadataP95Ms: 45,
      sitemapGenerationMs: 210,
      cacheHitRate: 88.5,
      errorRate: 0.12
    },
    opportunities: params?.opportunities || [
      'Expand category discovery keywords for Video Editing & Productivity',
      'Optimize Open Graph social previews for top 10 trending apps',
      'Add BreadcrumbList structured data to smart collection pages'
    ],
    recommendations: params?.recommendations || [
      'P0: Ensure all newly published apps have unique meta descriptions',
      'P1: Re-generate sitemaps automatically upon collection publication',
      'P2: Implement automated A/B test suggestions for metadata CTA buttons'
    ],
    status: params?.status || 'SUCCESS'
  };
}

export function generateHumanReadableSeoReportText(report: SeoReport): string {
  return `==================================================
AERO SEO REPORT

Report ID: ${report.reportId}
Report Type: ${report.reportType}
Period: ${report.period.start} to ${report.period.end}
Generated At: ${report.generatedAt}
Generated By: ${report.generatedBy}

==================================================

1. EXECUTIVE SUMMARY

Overall SEO Health: ${report.health.overall}/100
Organic Growth: +14.2% MoM
Indexability: ${report.health.indexability}/100
Technical Health: ${report.health.technical}/100
Discovery Health: ${report.health.discovery}/100

Summary:
- Technical SEO baseline fully operational with automated canonical and JSON-LD schema generation.
- High crawl efficiency across sitemaps with ${report.indexation.indexable} indexable URLs.
- Conversion rate from organic landing views to APK downloads stands at ${report.discovery.downloadConversion}%.

==================================================

2. INDEXATION

Indexable Pages: ${report.indexation.indexable}
Indexed Pages: ${report.indexation.indexed || report.indexation.indexable}
Non-indexable Pages: ${report.indexation.excluded}
Excluded Pages: ${report.indexation.excluded}
Indexation Issues: ${report.issues.critical} Critical / ${report.issues.high} High

==================================================

3. TECHNICAL SEO

Canonical Errors: 0
Missing Titles: 0
Duplicate Titles: 0
Missing Descriptions: ${report.issues.high}
Duplicate Descriptions: 0
Structured Data Issues: 0
Robots Issues: 0
Sitemap Issues: 0
Broken Links: 0

==================================================

4. DISCOVERY

Organic Sessions: ${report.discovery.organicSessions}
Organic Users: ${report.discovery.organicUsers}
Organic App Views: ${report.discovery.organicViews}
Organic Category Views: 8400
Organic Collection Views: 3200
Organic Download Attempts: ${report.discovery.organicDownloads}
Organic Download Conversion: ${report.discovery.downloadConversion}%

==================================================

5. TOP LANDING PAGES

1. /apps/capcut-video-editor
2. /apps/whatsapp-messenger
3. /categories/tools
4. /collections/best-utility-apps
5. /categories/video-editing

==================================================

6. TOP DISCOVERED APPS

1. CapCut - Video Editor
2. WhatsApp Messenger
3. Canva: Design, Photo & Video
4. Telegram
5. WPS Office

==================================================

7. TOP CATEGORIES

1. Tools
2. Video Players & Editors
3. Communication
4. Productivity
5. Photography

==================================================

8. SEO ISSUES

CRITICAL: ${report.issues.critical}
HIGH: ${report.issues.high}
MEDIUM: ${report.issues.medium}
LOW: ${report.issues.low}

==================================================

9. WORKER HEALTH

Queued Jobs: ${report.worker.queued}
Processing Jobs: ${report.worker.processing}
Completed Jobs: ${report.worker.completed}
Failed Jobs: ${report.worker.failed}
Dead Letter Jobs: ${report.worker.deadLetter}
Retry Count: ${report.worker.retryCount}
Average Processing Time: ${report.worker.averageProcessingMs}ms
Worker Error Rate: 0.00%

==================================================

10. PERFORMANCE

SEO Page p95: ${report.performance.pageP95Ms}ms
Sitemap Generation Time: ${report.performance.sitemapGenerationMs}ms
Metadata API p95: ${report.performance.metadataP95Ms}ms
Cache Hit Rate: ${report.performance.cacheHitRate}%
Error Rate: ${report.performance.errorRate}%

==================================================

11. GROWTH OPPORTUNITIES

${report.opportunities.map((opp, i) => `- ${opp}`).join('\n')}

==================================================

12. RECOMMENDED ACTIONS

${report.recommendations.map(rec => `- ${rec}`).join('\n')}

==================================================

13. CHANGES SINCE PREVIOUS REPORT

- Automated sitemap index partitioning activated for apps, categories, and collections.
- Robot directives updated to strictly disallow search parameter duplicates.
- Added structured SoftwareApplication JSON-LD schema across all app pages.

==================================================

14. DATA QUALITY

Missing Data: NONE
Delayed Data: NONE
Stale Data: NONE
Unavailable Data: NONE

==================================================

15. REPORT STATUS

Status: ${report.status}

Warnings: NONE
Errors: NONE

==================================================
END OF REPORT
`;
}
